/**
 * Average skill scores across active flinttype users (0–100 per axis),
 * overlaid on the skill radar so a user's shape reads as a comparison
 * rather than an arbitrary blob.
 *
 * AUTO-GENERATED by `yarn skills:baseline` from real data. The values
 * below are a sensible hand-set default until the command is first run
 * (SAMPLE = 0). Safe to commit; the command rewrites this whole file.
 */
export type SkillBaseline = {
  speed: number;
  accuracy: number;
  consistency: number;
  endurance: number;
};

export const SKILL_BASELINE: SkillBaseline = {
  speed: 24,
  accuracy: 65,
  consistency: 60,
  endurance: 26,
};

/** Users that fed the average (0 = default, never computed). */
export const SKILL_BASELINE_SAMPLE = 0;
/** Epoch ms the baseline was computed (0 = default). */
export const SKILL_BASELINE_COMPUTED_AT = 0;
