/**
 * Average skill scores across active flinttype users (0–100 per axis),
 * overlaid on the skill radar so a user's shape reads as a comparison
 * rather than an arbitrary blob.
 *
 * AUTO-GENERATED by `yarn skills:baseline` from real data; the values
 * below reflect the last run (SAMPLE users). Safe to commit.
 */
export type SkillBaseline = {
  speed: number;
  accuracy: number;
  consistency: number;
  endurance: number;
};

export const SKILL_BASELINE: SkillBaseline = {
  speed: 55,
  accuracy: 72,
  consistency: 45,
  endurance: 26,
};

/** Users that fed the average (0 = default, never computed). */
export const SKILL_BASELINE_SAMPLE = 16;
/** Epoch ms the baseline was computed (0 = default). */
export const SKILL_BASELINE_COMPUTED_AT = 1779353676817;
