import path from 'node:path';
import { PGlite } from '@electric-sql/pglite';
import { sql } from 'drizzle-orm';
import { drizzle } from 'drizzle-orm/pglite';
import { migrate } from 'drizzle-orm/pglite/migrator';
import * as schema from '@/db/schema/server';
import { createDatabase, type Database } from './index';

/**
 * Creates an in-memory Postgres (PGlite) with the committed server
 * migrations applied. Single source of truth — no inline DDL — so
 * schema changes generated by drizzle-kit flow into tests automatically.
 */
export async function createTestDatabase(): Promise<{
  db: Database;
  reset: () => Promise<void>;
  close: () => Promise<void>;
}> {
  const client = new PGlite();
  const drz = drizzle(client, { schema });
  await migrate(drz, {
    migrationsFolder: path.join(
      process.cwd(),
      'src',
      'db',
      'migrations',
      'server',
    ),
  });

  return {
    db: createDatabase(drz, 'pglite'),
    reset: async () => {
      await drz.execute(
        sql`TRUNCATE TABLE posts, users RESTART IDENTITY CASCADE`,
      );
    },
    close: async () => {
      await client.close();
    },
  };
}
