// For adding custom fonts with other frameworks, see:
// https://tailwindcss.com/docs/font-family
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Lora, IBM_Plex_Mono } from "next/font/google";
import { buildModeBootstrapScript } from "@/lib/themes/mode-bootstrap";
import { buildBootstrapScript } from "@/lib/themes/registry";
import "./globals.css";

const fontSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = Lora({
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          {/* Apply mode (light/dark) and the saved palette synchronously
              so neither flashes its default on first paint. Mode runs
              first so the palette script can read the resolved mode. */}
          <script
            dangerouslySetInnerHTML={{ __html: buildModeBootstrapScript() }}
          />
          <script
            dangerouslySetInnerHTML={{ __html: buildBootstrapScript() }}
          />
        </head>
        <body className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
