import { buildPageMetadata } from "@/server/seo";
import { AppChrome } from "../_components/app-chrome";
import { EditorialPage, EditorialSection } from "../_components/editorial-page";

export const metadata = buildPageMetadata({
  title: "Terms — using flinttype",
  description:
    "Plain-language terms of service for flinttype: free to use, MIT-licensed code, no warranty, fair-use guidelines.",
  path: "/terms",
});

export default function TermsPage() {
  return (
    <AppChrome>
      <EditorialPage
        eyebrow="Legal"
        title="Terms."
        subtitle="Short version: it's a free, open-source typing test. Use it, share it, fork it. Don't try to break it. Last updated 12 May 2026."
      >
        <EditorialSection title="The deal">
          <p>
            Flinttype is provided free of charge under the MIT license.
            You're welcome to use it for personal practice, classroom
            sessions, public competitions, or anything else that doesn't
            actively damage the service or other users.
          </p>
          <p>
            The source code lives on GitHub and is yours to fork,
            modify, or self-host within the MIT terms. You don't owe
            us attribution to use the hosted site.
          </p>
        </EditorialSection>

        <EditorialSection title="No warranty">
          <p>
            The site is offered as-is. We try hard to keep it fast and
            available, but we don't guarantee uptime, data
            preservation, or any specific level of accuracy in the
            adaptive engine. If your typing data matters to you, export
            it periodically.
          </p>
        </EditorialSection>

        <EditorialSection title="Fair use">
          <p>Don't:</p>
          <ul className="ml-4 flex list-disc flex-col gap-2 marker:text-muted-foreground/60">
            <li>
              Submit fabricated typing data, scripted scores, or any
              other run that wasn't generated by a real human at the
              keyboard. The leaderboard exists in good faith.
            </li>
            <li>
              Try to extract other users' personal data from the public
              endpoints. Public profile and leaderboard surfaces show
              what they show on purpose; everything else is private.
            </li>
            <li>
              Run automated load against the site beyond ordinary
              practice / race traffic.
            </li>
          </ul>
          <p>
            We may close accounts that violate the above without prior
            notice. Account closure removes the row from history and
            leaderboard but the deletion is intentional, not punitive.
          </p>
        </EditorialSection>

        <EditorialSection title="Account closure">
          <p>
            You can close your account any time — see the privacy
            page for the request flow. Closure is irreversible:
            re-signing-up later starts a fresh history, model, and
            personal-best record.
          </p>
        </EditorialSection>

        <EditorialSection title="Changes">
          <p>
            Substantive changes to these terms appear in the changelog
            with a one-line summary. Continuing to use the site after a
            change counts as acceptance of the new terms.
          </p>
        </EditorialSection>
      </EditorialPage>
    </AppChrome>
  );
}
