/**
 * Body of the skill-baseline recompute — see compute-skill-baseline.ts.
 *
 * Loads every test row, groups by user, and for each user with >=
 * MIN_TESTS completed runs computes their four skill axes via the same
 * `deriveSkills` the profile uses, then averages each axis across those
 * users. Writes the result to src/lib/skill-baseline.ts. Falls back to
 * the hand-set defaults when no user clears the threshold (empty dev DB).
 */
import { writeFileSync } from "node:fs";
import {
  deriveSkills,
  deriveTotals,
} from "@/app/profile/_components/derive-stats";
import { tests } from "@/db/schema/server/tests";
import { getDatabase } from "@/db/server";
import type { HistoryTest } from "@/types/history";

const MIN_TESTS = 5;
const OUT_PATH = "src/lib/skill-baseline.ts";
const DEFAULT = { speed: 24, accuracy: 65, consistency: 60, endurance: 26 };

export async function run() {
  const db = getDatabase();
  const rows = await db.$drizzle.select().from(tests);

  const byUser = new Map<string, HistoryTest[]>();
  for (const r of rows) {
    let list = byUser.get(r.userId);
    if (!list) {
      list = [];
      byUser.set(r.userId, list);
    }
    list.push({
      id: r.id,
      startedAtMs: r.startedAt.getTime(),
      completedAtMs: (r.completedAt ?? r.startedAt).getTime(),
      mode: r.mode,
      durationOrWordCount: r.durationOrWordCount,
      lengthMode: (r.lengthMode as "words" | "time" | "quote" | null) ?? null,
      wpm: r.wpm,
      accuracy: r.accuracy,
      errorCount: r.errorCount,
      wasCompleted: r.wasCompleted,
    });
  }

  const sums: Record<string, number> = {
    speed: 0,
    accuracy: 0,
    consistency: 0,
    endurance: 0,
  };
  let sample = 0;
  for (const list of byUser.values()) {
    if (list.filter((t) => t.wasCompleted).length < MIN_TESTS) continue;
    for (const s of deriveSkills(list, deriveTotals(list))) {
      sums[s.key] = (sums[s.key] ?? 0) + s.value;
    }
    sample += 1;
  }

  const avg = (k: keyof typeof DEFAULT) =>
    sample > 0 ? Math.round((sums[k] ?? 0) / sample) : DEFAULT[k];
  const baseline = {
    speed: avg("speed"),
    accuracy: avg("accuracy"),
    consistency: avg("consistency"),
    endurance: avg("endurance"),
  };

  const file = `/**
 * Average skill scores across active flinttype users (0–100 per axis),
 * overlaid on the skill radar so a user's shape reads as a comparison
 * rather than an arbitrary blob.
 *
 * AUTO-GENERATED by \`yarn skills:baseline\` from real data; the values
 * below reflect the last run (SAMPLE users). Safe to commit.
 */
export type SkillBaseline = {
  speed: number;
  accuracy: number;
  consistency: number;
  endurance: number;
};

export const SKILL_BASELINE: SkillBaseline = {
  speed: ${baseline.speed},
  accuracy: ${baseline.accuracy},
  consistency: ${baseline.consistency},
  endurance: ${baseline.endurance},
};

/** Users that fed the average (0 = default, never computed). */
export const SKILL_BASELINE_SAMPLE = ${sample};
/** Epoch ms the baseline was computed (0 = default). */
export const SKILL_BASELINE_COMPUTED_AT = ${Date.now()};
`;
  writeFileSync(OUT_PATH, file);
  console.log(
    `Wrote ${OUT_PATH} (sample=${sample} users):`,
    JSON.stringify(baseline),
  );
  process.exit(0);
}
