#!/usr/bin/env tsx
// Usage: yarn fonts:download
//
// Downloads every Google Font referenced in src/lib/fonts/catalog.ts to
// public/fonts/<id>/ and writes public/fonts/fonts.css with @font-face
// rules pointing at the local files. After this runs the typography
// picker no longer depends on fonts.googleapis.com / gstatic.com — every
// face ships with the app and works offline / in restricted networks.
//
// The script is idempotent: re-running re-fetches and overwrites.

import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { FONT_CATALOG, type FontEntry } from "../src/lib/fonts/catalog";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "..");
const OUT_DIR = path.join(ROOT, "public", "fonts");
const OUT_CSS = path.join(OUT_DIR, "fonts.css");

// Google's CSS2 endpoint hands back different `src:` formats based on UA:
// woff2 only for modern browsers, woff/ttf for older. Send a current
// Chrome string so we always land on the smallest woff2 payload.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

type Downloaded = { entry: FontEntry; css: string; bytes: number };

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`GET ${url} → ${res.status} ${res.statusText}`);
  return res.text();
}

async function fetchBinary(url: string): Promise<Uint8Array> {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`GET ${url} → ${res.status} ${res.statusText}`);
  return new Uint8Array(await res.arrayBuffer());
}

/** Walk every `url(https://fonts.gstatic.com/...woff2)` in the upstream
 *  CSS, download the file under public/fonts/<id>/, and rewrite the
 *  reference to a relative `./<id>/<basename>.woff2` path. The rest of
 *  the CSS (font-family, font-weight, font-style, unicode-range) is
 *  preserved verbatim so subsetting still works. */
async function localiseCss(entry: FontEntry, css: string): Promise<{
  css: string;
  bytes: number;
}> {
  const dir = path.join(OUT_DIR, entry.id);
  await mkdir(dir, { recursive: true });

  const urlRe = /url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/g;
  const matches = [...css.matchAll(urlRe)];
  if (matches.length === 0) {
    throw new Error(
      `${entry.family}: no woff2 urls found in upstream CSS — Google may have rejected the family name or the weights`,
    );
  }

  let total = 0;
  let counter = 0;
  const used = new Map<string, string>();

  for (const m of matches) {
    const remote = m[1];
    if (used.has(remote)) continue;
    counter += 1;
    // Google's hashed names (e.g. KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2) are
    // unique per subset, so just use the basename. Fall back to
    // `<id>-<n>.woff2` for the rare case Google ever serves an unnamed
    // file.
    const basename =
      path.basename(new URL(remote).pathname) || `${entry.id}-${counter}.woff2`;
    const dest = path.join(dir, basename);
    const bytes = await fetchBinary(remote);
    await writeFile(dest, bytes);
    total += bytes.byteLength;
    used.set(remote, `./${entry.id}/${basename}`);
  }

  const rewritten = css.replace(urlRe, (_match, remote: string) => {
    const local = used.get(remote);
    return local ? `url(${local})` : `url(${remote})`;
  });

  return { css: rewritten, bytes: total };
}

function fmtBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(2)} MB`;
}

async function main() {
  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  const downloaded: Downloaded[] = [];
  for (const entry of FONT_CATALOG) {
    process.stdout.write(`  ${entry.family.padEnd(22)} `);
    try {
      const upstream = await fetchText(entry.cssHref);
      const { css, bytes } = await localiseCss(entry, upstream);
      downloaded.push({ entry, css, bytes });
      process.stdout.write(`ok  ${fmtBytes(bytes)}\n`);
    } catch (err) {
      process.stdout.write(`FAIL ${(err as Error).message}\n`);
      throw err;
    }
  }

  const header =
    "/* Generated by scripts/fonts-download.ts — do not edit by hand.\n" +
    " * Run `yarn fonts:download` to refresh.\n" +
    " */\n";
  const body = downloaded
    .map(
      (d) =>
        `\n/* ─── ${d.entry.family} (${d.entry.category}) ─── */\n${d.css.trim()}\n`,
    )
    .join("");
  await writeFile(OUT_CSS, header + body, "utf8");

  const total = downloaded.reduce((acc, d) => acc + d.bytes, 0);
  console.log(
    `\nWrote ${downloaded.length} font(s) → ${path.relative(ROOT, OUT_CSS)} (${fmtBytes(total)} total)`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
